sudo: false
language: python
python:
- '2.7'
- '3.4'
- '3.5'
- '3.6'
before_script:
- pip install -e .
- pip install pep8
- pip install nose2
- pip install coverage
- pip install commonconf
- pip install python-coveralls
- pip install python-dateutil
script:
- pep8 uw_gradepage
- coverage run uw_gradepage/test.py -v
after_script:
- coveralls
before_deploy:
- find uw_gradepage/ -name \*.pyc -exec rm {} \;
- echo $TRAVIS_TAG > uw_gradepage/VERSION
deploy:
  provider: pypi
  server: https://testpypi.python.org/pypi
  user: uw-it-axdd
  skip_cleanup: true
  password:
    secure: X5IRiYrgUWLaU4byAUpa7kBaiwGMuhHLN/cbuRCvx9qNBLnQWxvFDLnOvQISoCNFsb8ipYgp2k7PbWGkUmJfyEaFEftfS4crbZidmEUEqdMA83QYjN2K1CbbNOAWQM5WWMlu6DlIgmDTY8TH/6BsCLiwNjPQ4FA5ElmSdMw48gxquKsHCuwk+6H5in6kNgAfTJPQamKJd0xDGA813Z15f96eGtM9BdHaWzlE2Uwztv3on3PbrHxh5EkJCRRV+cL4e34b6ymaDHvkwvR2O17z42Yt9C6Snk5N3szWF4D+B/MQAg8zUpHD6bXIWnUvlyive5HvYmbQcFSHum7KwfK352/uGgjkcZFgYLakjvX/v1PnqR4goy3cjujYP1owK9Nz4o9786Fs997sEem/eWcvZZmhGKpp2BeK6w2F673z19tw//Vzg5oxFCS8GMm+k1JOakZFI0Hjg4y4Iva4jxSW0zpOAEAQMlW+dOv0GQcDJaR49nb6JTwJHfKFt+gmlGD/5HDEREiSNvJHo5qPKC/phzSY3HOs4el9/b8nel1q0srKXQ80O2yFypHHQjrEJzvGZhygApq2pANlZNakxIQi4PMWpqvSmvr+qgRookeDpjcH5ILv1Ei9WY70bKojKU7ZjIrN0wbnXf3kH3Soar1rxHNCeqT40CEgdiqWjdlhoa8=
  on:
    tags: true
    python: '3.5'
