sudo: false
language: python
python:
- '2.7'
- '3.4'
- '3.5'
- '3.6'
before_script:
- pip install -e .
- pip install pep8
- pip install nose2
- pip install coverage
- pip install commonconf
- pip install python-coveralls
- pip install python-dateutil
script:
- pep8 uw_gradepage
- coverage run uw_gradepage/test.py -v
after_script:
- coveralls
before_deploy:
- find uw_gradepage/ -name \*.pyc -exec rm {} \;
- echo $TRAVIS_TAG > uw_gradepage/VERSION
deploy:
  provider: pypi
  user: uw-it-aca
  skip_cleanup: true
  password:
    secure: IA07PguUVKcCZLHW6htXux5Hi5mdzfFmTZkMutHRNjTldVr8qa6LY1fHSk3ZvwVe4LyvIvOL/D+o3FsvMXN4zvMFmPVCLNgZI8rmLx+HOEJPdDI3hcxeE6IzoezREpL4MZkXmhf8Q9KNJN1FaeyLzuh0bonfvzffNfJa0YHluZsfi9D/KT6MC0kdWjtpVuH/le0JqQqBcgMYEYGq3STHDx7jDCVa6RJrgGuvTMB/cFzEASfBte9gtTuL0Hqh+9eHP6iOgBeGCnY1fwGPvly3N+VOkJ1NDEGgQpfS3AdogUBGTx0BZZHIStiYMIDr7JiQqXqcfbEEzhIy/0oY3qHSCTeqohjEhmGUSGMuJLbzKPO8zS4ZWskYwaRLQZW1WafR5dLlv/W3RGvaz3/Zw6duv9q6u4hCBAnCN4qYUp3qpYPRRiSaqOLGUELCt+ub627EY94jYiiNkbHug0Ssp9PSbBBzNe8n+xXJekQmbU0TFMgzBp4/83xMRcycXTBt4zsRZBfdotHRjsZHtD/QgiFv1zux9uU8hqaVckC7o2WV2gf/0a5DUme9ScheLkNYbfRgsqEf5l66YjI5m3KsA6VtFClGpnn27GozMsL8s6LNu/6UARds8tLgCy/nqo6CafHk8sMBcBaEGWQjT1F4ENbn9ria4mkfvHMvTIfKpq03+q8=
  on:
    tags: true
    python: '3.5'
